version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "../:/root/shell-oneliner"
      - "./config:/root"
    ports:
      - "3033:3033"
